server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.28:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.28:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 122.112.137.108
    port: 6379
    # redis数据库索引，默认为2
    database: 1
    password: al123456
    timeout: 5000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 100
        max-idle: 8
        max-wait: -1
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
